version: '3.3'
services:

  node:
    image: node:10.16.2
    ports:
      - 3000:3000
    working_dir: /var/www
    command: ['yarn', 'start']
    volumes:
      - ../node-js-dev-test:/var/www
    restart: unless-stopped
    depends_on:
      - mysql

  mysql:
    image: mysql:5.6
    volumes:
      - mysql-data:/data
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: apidb
    restart: unless-stopped

  adminer:
    image: adminer:4.7.2
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - mysql

volumes:
  mysql-data: